name: Build

on:
  push:
    branches: ["main", "master"]

env:
  IMAGE_NAME: rust_actix_diesel

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: docker build -t $IMAGE_NAME $IMAGE_NAME

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Publish to registry
        run: docker push ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest
